# Generated by Django 2.2.6 on 2019-11-24 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id_barang', models.AutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=30)),
                ('distributor', models.CharField(max_length=30)),
                ('deskripsi_barang', models.CharField(max_length=500)),
                ('jumlah_barang', models.IntegerField()),
                ('satuan', models.CharField(max_length=10)),
                ('harga_beli', models.IntegerField()),
                ('harga_jual', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id_accountant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pendapatan',
            fields=[
                ('id_pendapatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=30)),
                ('nama_pembeli', models.CharField(max_length=30)),
                ('jumlah_pembelian', models.IntegerField()),
                ('deskripsi_pendapatan', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id_accountant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desk.Barang')),
            ],
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id_pengeluaran', models.AutoField(primary_key=True, serialize=False)),
                ('deskripsi_pengeluaran', models.CharField(max_length=500, null=True)),
                ('biaya', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id_accountant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Piutang',
            fields=[
                ('id_piutang', models.AutoField(primary_key=True, serialize=False)),
                ('asal_piutang', models.CharField(max_length=20)),
                ('deskripsi_piutang', models.CharField(max_length=500, null=True)),
                ('jumlah_piutang', models.IntegerField()),
                ('jatuh_tempo', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id_accountant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id_profit', models.AutoField(primary_key=True, serialize=False)),
                ('pengeluaran_bulanan', models.IntegerField()),
                ('pendapatan_bulanan', models.IntegerField()),
                ('total_profit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id_accountant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_pendapatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desk.Pendapatan')),
                ('id_pengeluaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desk.Pengeluaran')),
                ('id_piutang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desk.Piutang')),
            ],
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
