# Generated by Django 2.2.7 on 2019-11-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendapatan',
            name='total_pendapatan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='nama_barang',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='pendapatan',
            name='nama_barang',
            field=models.CharField(max_length=20),
        ),
    ]
